version: "3"
services:
  web:
    build: .
    ports:
      - "9080:80"
    environment:
      DATABASE_URL: sqlite:////data/db.sqlite3
      MEALPLANNER_SECRET_KEY:
    volumes:
      - mealplanner-data:/data
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealplanner.rule=Host(`mealplanner.simonrw.com`)"
      - "traefik.http.routers.mealplanner.entrypoints=websecure"
      - "traefik.http.routers.mealplanner.tls.certresolver=myresolver"
volumes:
  mealplanner-data:
