"""empty message

Revision ID: 57688a7ca9ed
Revises: 45ff5de91f9e
Create Date: 2021-04-18 02:26:53.099238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57688a7ca9ed"
down_revision = "45ff5de91f9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("membership", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("count", sa.Integer(), nullable=False, server_default="-1")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("membership", schema=None) as batch_op:
        batch_op.drop_column("count")

    # ### end Alembic commands ###
