"""empty message

Revision ID: 667d932dde3f
Revises: 0d13c9c8d962
Create Date: 2021-04-25 00:48:49.644369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667d932dde3f'
down_revision = '0d13c9c8d962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocation', schema=None) as batch_op:
        batch_op.create_unique_constraint('idx_allocation_meal_day', ['meal', 'day'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocation', schema=None) as batch_op:
        batch_op.drop_constraint('idx_allocation_meal_day', type_='unique')

    # ### end Alembic commands ###
