"""empty message

Revision ID: b582eec973b2
Revises: 92c9847fdcb6
Create Date: 2021-04-18 01:47:24.052406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b582eec973b2'
down_revision = '92c9847fdcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.create_unique_constraint("idx_unique_name", ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_constraint("idx_unique_name", type_='unique')

    # ### end Alembic commands ###
